### ISSUE TITLE
humidity

### ISSUE THREAD

**Issue by skyw33** [Noltari/aioairzone#7]
Not a bug.  Just trying to get more information.  I have a mitsubishi heat pump hvac and an aidoo pro.  The humidity is giving me a "0" value when making a POST call to the api.  My understanding is that this is a known issue, but can you help me understand the source of the problem?  Is this just due to the fact that airzone is not making this information accessible through the api?

**Comment by Noltari** [comment]
> Not a bug. Just trying to get more information. I have a mitsubishi heat pump hvac and an aidoo pro. The humidity is giving me a "0" value when making a POST call to the api. My understanding is that this is a known issue, but can you help me understand the source of the problem? Is this just due to the fact that airzone is not making this information accessible through the api?

The problem is that in most of this configurations, the HVAC device doesn't provide the humidity value to Airzone, but Airzone is probably providing a 0 value because AFAIK they give you the possibility to connect an Airzone thermostat to the Aidoo Pro, and if this is not the case, then the humidity is exposed as 0 on the Local API.
Therefore, in those cases in which the humidity isn't provided and no Airzone thermostat is connected, the Local API shouldn't expose the humidity value at all, but since they are exporting it what I did in the integration library is to discard the 0 value and pretend that there's no humidity provided...

**Comment by skyw33** [comment]
Thank you -- I appreciate the detail.  I will just setup a separate humidity sensor then.
